// Generated by corpus.test.ts from the docs pages; refresh with `pnpm vitest run lib/docs-chat -u`.
export const DOCS_CORPUS: readonly { href: string; title: string; text: string }[] = [
  {
    href: "/docs",
    title: "Introduction",
    text: `Documentation

# LintCat

An AI reviewer that reads your pull requests and leaves inline review comments, plus an AI PR Review check run with the full summary. Install the GitHub App and add a model key. Nothing goes in your CI.

[Quickstart](/docs/quickstart) [Install the GitHub App](https://github.com/apps/LintcatPR/installations/new) [Open the dashboard](/dashboard)

## What it does {#what-it-does}

One reviewer reads each pull request in a single pass, looking for correctness, security, performance, test and documentation problems. You don’t need to configure anything to get that.

A finding can include a **suggested fix**. LintCat checks the fix against the file at the pull request’s latest commit before offering it, so a suggestion never lands on the wrong lines. Apply it with one click, or have LintCat commit it for you.

## Getting it on your repositories {#getting-it}

Install the LintCat GitHub App on your personal account or an organization, and pick the repositories it may review. An owner of the account saves one Anthropic or OpenAI API key on the dashboard; reviews run on that key, so model usage is billed to your provider account.

By default every pull request is reviewed when it is opened, and again on every push. Switch a repository to review only pull requests with the \`ai-review\` label, or turn it off, from its settings page. A new push replaces a review still in progress, so comments are always on the latest commit.

**Note: No workflow file, no secrets in GitHub** Reviews run on LintCat’s side. Your repository gets no workflow, and your Actions minutes go untouched.

## What the reviewer looks for {#reviewer}
- **Correctness** — Logic errors, wrong bounds, unhandled null, broken error handling
- **Security** — Auth, cross-tenant access, injection, secret leakage, privilege
- **Performance** — N+1 queries, unbounded reads, quadratic scans, blocking I/O
- **Tests** — Branches this change adds or changes and leaves untested
- **Documentation** — Documentation this change made wrong

## Keep reading {#keep-reading}

[Quickstart: Install the GitHub App, add a model key, label a pull request.](/docs/quickstart)

[Configuration: The model key, when each repository is reviewed, models and fixes.](/docs/configuration)

[How LintCat works: What it looks for, and how it differs.](/docs/how-it-works)

[Security: What LintCat can access, and what it never does.](/docs/security)

[MCP server: The same review over a working tree, inside your coding agent.](/docs/mcp-server)`,
  },
  {
    href: "/docs/quickstart",
    title: "Quickstart",
    text: `Start here

# Quickstart

Three steps, a few minutes, and nothing to commit to your repository.

## 1. Install the GitHub App {#install}

Install LintCat on your personal GitHub account or on an organization, and choose all repositories or only some. You don’t need an organization: your own account works on its own. GitHub then sends you back to the dashboard, signed in, with the account set up.

[Install the GitHub App](https://github.com/apps/LintcatPR/installations/new)

**Note: Not an owner?** If you install on an organization you don’t own, GitHub sends the install to an owner to approve. Once they do, sign in again and the organization shows up.

## 2. Add a model key {#key}

On the dashboard, open **Settings** in the sidebar, pick Anthropic or OpenAI and paste an API key. Only owners of the account see this page. The key is stored encrypted and never shown again; the dashboard shows only its last four characters.

Until a key is saved, a pull request that would be reviewed gets a neutral check run asking an owner to add one, and no model is called.

## 3. Review a pull request {#review}

Open a pull request on an installed repository. The review runs in the background and posts when it finishes, and every later push to that pull request is reviewed again.

To review only the pull requests you pick, switch the repository to the \`ai-review\` label on its settings page. See [Configuration](/docs/configuration).

## What lands on the pull request {#result}
- Inline review comments on the lines the findings point at, one per finding.
- An \`AI PR Review\` check run with the full summary. Its conclusion is \`neutral\` whenever there are findings. The review is advisory and never blocks a merge.
- One-click suggested changes wherever a finding carried a fix that checked out against the latest commit.
- The review, its findings and its token spend, on your dashboard.`,
  },
  {
    href: "/docs/configuration",
    title: "Configuration",
    text: `Using LintCat

# Configuration

Everything is set on the dashboard. One model key per account, and a few settings per repository.

## Model key {#model-key}

Reviews run on the account’s own Anthropic or OpenAI API key. An owner of the account (on a personal account, you) sets it under **Settings** in the dashboard sidebar; other members don’t see that page.

The key is stored encrypted and only the review service ever reads it back. The dashboard shows the provider and the last four characters, nothing more. Replacing the key takes effect on the next review; removing it stops reviews until a new one is added.

## Repository settings {#repositories}

Each repository has a **Settings** page, linked from the repository on the dashboard. Anyone who can see the repository can view it; account owners and people with admin or maintain access to the repository can change it.
| When reviews run | What happens |
| Every pull request | Default. Every pull request is reviewed when it is opened or reopened, and on every push. |
| On the ai-review label | A pull request is reviewed when it gets the label, and on every push while it carries it. |
| Off | Nothing is reviewed. The repository's past reviews stay on the dashboard. |

**Note: A push replaces a review in progress** If a pull request gets a new commit while it is being reviewed, the older review is dropped before it posts anything and the new commit is reviewed instead.

## Models {#models}

Each repository uses the provider default unless you pick a model on its settings page. The choices follow the provider of the account’s key:
| Provider | Models |
| Anthropic | claude-sonnet-5, claude-haiku-4-5, claude-sonnet-4-5 |
| OpenAI | gpt-5.6-luna, gpt-5.6-luna-mini |

**Note: Switched providers?** A model chosen for the old provider won’t run on the new key. Reviews on that repository fail with a check run naming the model until you pick another one, or go back to the provider default.

## Fixes {#fixes}

With **Commit verified fixes** off, the default, a finding’s fix arrives as a one-click suggested change on its review comment. Turn it on and LintCat commits the fixes to the pull request branch itself, in one commit.

Fixes are never force-pushed. If someone pushed while the review was running, the commit is skipped and the fixes arrive as suggestions instead.

## What the App can access {#permissions}

GitHub shows these when you install the App. It never approves or merges a pull request, and it only writes file contents when you turn fixes on.
| Permission | Access | Used for |
| Contents | Read and write | Reads the files a review needs. Writes only to commit fixes, when you turn fixes on. |
| Pull requests | Read and write | Reads the pull request and posts the inline review comments. |
| Checks | Read and write | Publishes the AI PR Review check run. |
| Organization members | Read | Decides who can see the organization on the dashboard. |
| Metadata, email addresses | Read | Lists repositories and signs you in. |`,
  },
  {
    href: "/docs/how-it-works",
    title: "How LintCat works",
    text: `How it works

# How LintCat works

LintCat reads a pull request the way a careful reviewer would: the diff, the code around it, and the parts of the repository it touches.

## How a review works {#review}

A review runs in eight stages. Each one below is drawn step by step, in the order it happens; the drawings loop, and every frame is generated from code, so what you see is what the pipeline does.

After the first review, a new push is reviewed from the commits added since, and findings nobody has resolved stay listed on the check run.

## 1. GitHub knocks {#stage01-webhook}

Stage 1GitHub knocks:

GitHub sends a \`pull_request\` event to LintCat’s webhook. The request is checked three ways before anything runs: the HMAC signature over the raw body, the shape of the payload, and the repository’s review mode. A repository set to label is reviewed only when the pull request carries the \`ai-review\` label.

## 2. One job per head {#stage02-queue}

Stage 2One job per head:

One job is queued per head commit. A newer push to the same pull request supersedes the older job, and a repeat delivery of the same event is a no-op. The web app pings the worker, a scheduler sweeps for anything a ping missed, and the worker claims one job at a time.

## 3. Lease, token, key {#stage03-boot}

Stage 3Lease, token, key:

Before the first model call the worker renews its lease on a heartbeat, mints a GitHub App installation token, confirms the head has not moved, decrypts your organisation’s model key and picks the provider and model. With no key it posts a neutral check run asking for one, and stops.

## 4. Only what changed since {#stage04-scope}

Stage 4Only what changed since:

The pull request, its changed files and its diff are fetched in parallel. The baseline is the last commit that already carries LintCat’s check run: only files changed since then are reviewed, and any doubt widens the scope back to the whole pull request. Findings nobody resolved are carried forward.

## 5. Trace the blast radius {#stage05-blast}

Stage 5Trace the blast radius:

The repository is indexed at the base commit from a single tarball: what each file is, which test covers it, the import graph, cycles and entry points. From every changed file the blast radius walks importers up to three hops out, flags untested sources, broken importers and cycles, and scores the risk from 0 to 100. The score and the graph appear on the check run and on the dashboard.

## 6. Read, then propose {#stage06-agent}

Stage 6Read, then propose:

One reviewer agent receives the repository summary, the index, the imports and the diff, and eight read-only tools for opening files, searching, and finding references. It has at most twelve turns, and its final answer must be JSON that parses. In parallel, reviewer suggestions come from blame at the base commit and CODEOWNERS.

## 7. Every finding checked {#stage07-check}

Stage 7Every finding checked:

Everything the model proposed is untrusted until checked. A finding survives only if it has the right shape, stays in its own category, points at a file in the pull request and a line that was added, is confident enough and is not a duplicate; at most ten are kept. A fix is kept only when the lines it replaces match the file at head byte for byte.

## 8. Post, record, settle {#stage08-publish}

Stage 8Post, record, settle:

Rendering is a pure step with no I/O. Writes go in order: a fast-forward fix commit if fixes are on, then inline comments, then the check run, which is always neutral and never blocks a merge. The review, its findings, the risk and the graph snapshot are recorded for the dashboard, and the job is marked complete, superseded, retried or failed.

## What it looks for {#looks-for}
- **Correctness:** wrong conditions or bounds, unhandled empty input, swallowed errors, missing awaits, ordering bugs.
- **Security:** missing or bypassable auth, cross-tenant access, injection, leaked secrets, sensitive data in logs.
- **Performance:** N+1 queries, unbounded reads on a request path, quadratic scans over growing data.
- **Tests:** a new branch the module’s tests don’t exercise, or a test still asserting the old behaviour.
- **Documentation:** a README, doc or comment the change made wrong.

It leaves style, formatting, naming and architectural taste to your linter and your team. It reports a problem only when it can say concretely what goes wrong, and when.

## Keeping the codebase in line {#in-line}

A diff only shows what changed. Before the reviewer starts, LintCat maps the repository’s imports, so for every changed file the reviewer already knows:
- what kind of file it is, and which package owns it;
- which test covers it, or that nothing does;
- how many files import it;
- whether it is dead, with nothing importing it and no entry point reaching it;
- whether it sits in an import cycle.

It can also look up which files use a name that changed, and which files have historically changed alongside this one. That is how it catches the caller that wasn’t updated, the test that no longer covers the code, and the doc that now describes something else.

## How it's different {#different}
- **Nothing unchecked reaches your pull request.** Every finding and fix is checked before it posts. See [Security](/docs/security).
- **It can’t change your repository.** The AI reviewer can only read. Comments, and fixes if you turn them on, are posted by LintCat after the checks.
- **Fixes are proven, not guessed.** A fix is only offered when the lines it replaces match the file exactly, so a suggestion never lands on the wrong code.
- **The branch can’t mislead it.** LintCat maps your repository as it was before the pull request, so a change can’t misrepresent the rest of your code.
- **It never blocks a merge.** The check run is advisory.
- **Your model, nothing in CI.** Install the GitHub App and add a model key. There is no workflow file to maintain.`,
  },
  {
    href: "/docs/security",
    title: "Security",
    text: `How it works

# Security

LintCat reads your code to review it, and that is all the AI part can do. Everything it posts is checked first, and it never approves, merges or blocks anything.

## What LintCat can access {#access}
- **Only the repositories you pick** when you install the GitHub App. The permissions it asks for, and why, are listed under [Configuration](/docs/configuration#permissions).
- **Your model provider sees the code it reviews.** Reviews run on your account’s own Anthropic or OpenAI key, under your agreement with that provider.
- **Your key stays encrypted.** Only the review service reads it back; the dashboard shows its last four characters and nothing more.

## What it never does {#never}
- **The AI reviewer can only read.** It can look through your code but has no way to comment, commit, approve or merge. Posting the review is done by LintCat itself, after the checks below.
- **It never blocks a merge.** The AI PR Review check is advisory, and its conclusion is \`neutral\` when there are findings.
- **It never force-pushes.** Fixes are committed only when you turn that on, and only if nobody pushed while the review ran. Otherwise they arrive as suggestions.

## Only findings worth reading {#quality}

Before anything is posted, every finding has to pass these checks:
- It points at a line this pull request added or changed.
- The reviewer is confident in it.
- It doesn’t repeat another finding.
- It makes the cut of at most 10 per review, most important first.

## Fixes you can trust {#fixes}

A suggested fix is offered only when the lines it replaces match the file at the pull request’s latest commit exactly, so it never lands on the wrong code. Fixes stay inside the changed code and small enough to review at a glance.

**Note: A bad fix doesn't cost the finding** If a fix doesn’t check out, you still get the comment, just without the suggestion.

## Prompt injection {#injection}

Pull requests can contain text written to steer an AI. LintCat treats everything in the repository, including the title, description, diff and files, as code to review and never as instructions. And since the reviewer can only read, text like that has nothing it could make LintCat do.`,
  },
  {
    href: "/docs/mcp-server",
    title: "MCP server",
    text: `Reference

# MCP server

Runs the reviewer inside a coding agent such as Claude Code, over local stdio, so a change is reviewed before it is pushed.

## Running it {#running}

Register it in any MCP client as a local stdio server named \`pr-review\`. It needs an \`ANTHROPIC_API_KEY\` or \`OPENAI_API_KEY\`; GitHub access uses \`GITHUB_TOKEN\` or the \`gh\` login.

## Tools {#tools}
| Tool | What it does |
| review_local_changes | Reviews the working tree against its base branch — commits since the merge-base plus uncommitted and untracked files — before anything is pushed. |
| review_pull_request | Reviews a GitHub pull request; a dry run unless publish: true, which posts the check run and comments as the GitHub App would. |
| repository_overview, find_references, describe_file | The repository index, built from the working tree, with no network. |
| list_reviews, get_review, review_trends | Stored review history, scoped by the dashboard's own access rules to your GitHub account. |

**Note: You can cancel** Cancelling in your client stops the review straight away, and a cancelled review posts nothing.

## The same review as the App {#same-path}

A local review is the same review the GitHub App runs, with the same checks on every finding and fix. It reads your local checkout instead of GitHub, and runs on your machine with your own key, not the account’s.`,
  },
];
