import { createElement, type ComponentType } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";

import Configuration from "@/app/(docs)/docs/configuration/page";
import HowItWorks from "@/app/(docs)/docs/how-it-works/page";
import McpServer from "@/app/(docs)/docs/mcp-server/page";
import Introduction from "@/app/(docs)/docs/page";
import Quickstart from "@/app/(docs)/docs/quickstart/page";
import Security from "@/app/(docs)/docs/security/page";
import { DOCS_PAGES } from "@/lib/docs";
import { htmlToCorpusText } from "@/lib/docs-chat/html-to-text";

const PAGES: Record<string, ComponentType> = {
  "/docs": Introduction,
  "/docs/quickstart": Quickstart,
  "/docs/configuration": Configuration,
  "/docs/how-it-works": HowItWorks,
  "/docs/security": Security,
  "/docs/mcp-server": McpServer,
};

function templateLiteral(text: string): string {
  return `\`${text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")}\``;
}

function corpusModule(): string {
  const entries = DOCS_PAGES.map((page) => {
    const Page = PAGES[page.href];
    if (!Page) throw new Error(`no page component for ${page.href}`);
    const text = htmlToCorpusText(renderToStaticMarkup(createElement(Page)));
    return [
      "  {",
      `    href: ${JSON.stringify(page.href)},`,
      `    title: ${JSON.stringify(page.title)},`,
      `    text: ${templateLiteral(text)},`,
      "  },",
    ].join("\n");
  });
  return [
    "// Generated by corpus.test.ts from the docs pages; refresh with `pnpm vitest run lib/docs-chat -u`.",
    "export const DOCS_CORPUS: readonly { href: string; title: string; text: string }[] = [",
    ...entries,
    "];",
    "",
  ].join("\n");
}

describe("docs corpus", () => {
  it("has a page component for every page in the nav", () => {
    expect(Object.keys(PAGES).sort()).toEqual(DOCS_PAGES.map((page) => page.href).sort());
  });

  it("matches the pages as they render now", async () => {
    await expect(corpusModule()).toMatchFileSnapshot("./corpus.ts");
  });
});
