import type { FileKind, MapGraph, MapNode } from "@/lib/codebase-map-view";

// This repository, roughly, with the current design PR as the "changed" set.
const FILES: [string, FileKind, number, Partial<MapNode>?][] = [
  ["apps/web/app/layout.tsx", "source", 2, { changed: true }],
  ["apps/web/app/(docs)/page.tsx", "source", 4, { changed: true }],
  ["apps/web/app/(docs)/layout.tsx", "source", 2],
  ["apps/web/app/(docs)/docs/agents/page.tsx", "source", 3],
  ["apps/web/app/(docs)/docs/configuration/page.tsx", "source", 4],
  ["apps/web/app/(apex)/dashboard/page.tsx", "source", 4],
  ["apps/web/app/o/[slug]/page.tsx", "source", 5, { changed: true }],
  ["apps/web/app/o/[slug]/layout.tsx", "source", 2],
  ["apps/web/app/o/[slug]/analytics/page.tsx", "source", 4],
  ["apps/web/app/o/[slug]/reviews/[id]/page.tsx", "source", 5],
  ["apps/web/app/api/ingest/handler.ts", "source", 4],
  ["apps/web/app/api/ingest/handler.test.ts", "test", 3],
  ["apps/web/app/api/github/webhook/handler.ts", "source", 5],
  ["apps/web/app/api/github/webhook/handler.test.ts", "test", 4],
  ["apps/web/components/shell/topbar.tsx", "source", 2, { changed: true }],
  ["apps/web/components/shell/topbar-frame.tsx", "source", 2, { changed: true }],
  ["apps/web/components/shell/sidebar.tsx", "source", 3],
  ["apps/web/components/shell/page-header.tsx", "source", 2],
  ["apps/web/components/docs/prose.tsx", "source", 3, { changed: true }],
  ["apps/web/components/docs/article.tsx", "source", 2, { changed: true }],
  ["apps/web/components/docs/docs-nav.tsx", "source", 3, { changed: true }],
  ["apps/web/components/docs/toc.tsx", "source", 2, { changed: true }],
  ["apps/web/components/charts/chart-frame.tsx", "source", 2],
  ["apps/web/components/charts/series.ts", "source", 2],
  ["apps/web/components/charts/severity-trend-chart.tsx", "source", 3],
  ["apps/web/components/review/findings-table.tsx", "source", 5],
  ["apps/web/components/review/finding-sheet.tsx", "source", 4],
  ["apps/web/components/ui/severity-badge.tsx", "source", 1],
  ["apps/web/components/ui/stat.tsx", "source", 2],
  ["apps/web/lib/paths.ts", "source", 2],
  ["apps/web/lib/paths.test.ts", "test", 2],
  ["apps/web/lib/docs.ts", "source", 2],
  ["apps/web/lib/docs.test.ts", "test", 1],
  ["apps/web/lib/session.ts", "source", 2],
  ["apps/web/lib/codebase-map.ts", "source", 3, { changed: true }],
  ["apps/web/lib/codebase-map.test.ts", "test", 3, { changed: true }],
  ["packages/design/src/theme.css", "config", 5, { changed: true }],
  ["packages/design/src/brand.css", "config", 3, { changed: true }],
  ["packages/design/src/index.ts", "source", 2, { changed: true }],
  ["packages/design/src/cn.ts", "source", 1],
  ["packages/design/src/components/button.tsx", "source", 2, { changed: true }],
  ["packages/design/src/components/badge.tsx", "source", 1, { changed: true }],
  ["packages/design/src/components/input.tsx", "source", 1, { changed: true }],
  ["packages/design/src/components/card.tsx", "source", 2],
  ["packages/design/src/components/table.tsx", "source", 2],
  ["packages/design/src/components/chart.tsx", "source", 4, { changed: true }],
  ["packages/design/src/theme.test.ts", "test", 2, { changed: true }],
  ["packages/db/src/schema.ts", "source", 5],
  ["packages/db/src/dashboard.ts", "source", 5],
  ["packages/db/src/client.ts", "source", 1],
  ["packages/db/src/dashboard.test.ts", "test", 3],
  ["packages/reviewer/src/review.ts", "source", 6],
  ["packages/reviewer/src/synthesis.ts", "source", 4],
  ["packages/reviewer/src/incremental.ts", "source", 3],
  ["packages/reviewer/src/review.test.ts", "test", 5],
  ["packages/ai/src/agent.ts", "source", 5, { cycle: true }],
  ["packages/ai/src/tools.ts", "source", 3, { cycle: true }],
  ["packages/ai/src/prompts.ts", "source", 4],
  ["packages/ai/src/agent.test.ts", "test", 3],
  ["packages/github/src/client.ts", "source", 4],
  ["packages/github/src/comments.ts", "source", 2],
  ["packages/github/src/client.test.ts", "test", 2],
  ["packages/index/src/index.ts", "source", 5],
  ["packages/index/src/references.ts", "source", 3],
  ["packages/index/src/legacy-walk.ts", "source", 2, { dead: true }],
  ["packages/schemas/src/findings.ts", "source", 2],
  ["packages/schemas/src/config.ts", "source", 2],
  ["packages/logging/src/logger.ts", "source", 1],
  ["apps/action/src/main.ts", "source", 3],
  ["apps/mcp/src/server.ts", "source", 3],
  ["apps/cli/src/main.ts", "source", 2],
  ["docs/adr/0002-primer-tokens-under-shadcn.md", "docs", 2, { changed: true }],
  ["docs/incremental-review.md", "docs", 1],
  ["README.md", "docs", 2],
  ["CLAUDE.md", "docs", 1, { changed: true }],
];

const EDGES: [string, string][] = [
  ["apps/web/app/layout.tsx", "packages/design/src/index.ts"],
  ["apps/web/app/layout.tsx", "packages/design/src/theme.css"],
  ["packages/design/src/theme.css", "packages/design/src/brand.css"],
  ["packages/design/src/index.ts", "packages/design/src/components/button.tsx"],
  ["packages/design/src/index.ts", "packages/design/src/components/badge.tsx"],
  ["packages/design/src/index.ts", "packages/design/src/components/input.tsx"],
  ["packages/design/src/index.ts", "packages/design/src/components/card.tsx"],
  ["packages/design/src/index.ts", "packages/design/src/components/table.tsx"],
  ["packages/design/src/components/button.tsx", "packages/design/src/cn.ts"],
  ["packages/design/src/components/badge.tsx", "packages/design/src/cn.ts"],
  ["packages/design/src/components/input.tsx", "packages/design/src/cn.ts"],
  ["packages/design/src/components/chart.tsx", "packages/design/src/cn.ts"],
  ["packages/design/src/theme.test.ts", "packages/design/src/brand.css"],
  ["apps/web/app/(docs)/page.tsx", "apps/web/components/docs/prose.tsx"],
  ["apps/web/app/(docs)/page.tsx", "apps/web/lib/docs.ts"],
  ["apps/web/app/(docs)/layout.tsx", "apps/web/components/docs/docs-nav.tsx"],
  ["apps/web/app/(docs)/docs/agents/page.tsx", "apps/web/components/docs/article.tsx"],
  ["apps/web/app/(docs)/docs/configuration/page.tsx", "apps/web/components/docs/article.tsx"],
  ["apps/web/components/docs/article.tsx", "apps/web/components/docs/toc.tsx"],
  ["apps/web/components/docs/article.tsx", "apps/web/components/docs/prose.tsx"],
  ["apps/web/components/docs/docs-nav.tsx", "apps/web/lib/docs.ts"],
  ["apps/web/lib/docs.test.ts", "apps/web/lib/docs.ts"],
  ["apps/web/app/(apex)/dashboard/page.tsx", "apps/web/components/shell/topbar.tsx"],
  ["apps/web/components/shell/topbar.tsx", "apps/web/components/shell/topbar-frame.tsx"],
  ["apps/web/components/shell/topbar.tsx", "apps/web/components/shell/sidebar.tsx"],
  ["apps/web/components/shell/topbar.tsx", "apps/web/lib/paths.ts"],
  ["apps/web/components/shell/sidebar.tsx", "apps/web/lib/paths.ts"],
  ["apps/web/lib/paths.test.ts", "apps/web/lib/paths.ts"],
  ["apps/web/app/o/[slug]/layout.tsx", "apps/web/components/shell/sidebar.tsx"],
  ["apps/web/app/o/[slug]/layout.tsx", "apps/web/lib/session.ts"],
  ["apps/web/app/o/[slug]/page.tsx", "apps/web/components/ui/stat.tsx"],
  ["apps/web/app/o/[slug]/page.tsx", "apps/web/components/shell/page-header.tsx"],
  ["apps/web/app/o/[slug]/page.tsx", "packages/db/src/dashboard.ts"],
  ["apps/web/app/o/[slug]/analytics/page.tsx", "apps/web/components/charts/severity-trend-chart.tsx"],
  ["apps/web/app/o/[slug]/analytics/page.tsx", "packages/db/src/dashboard.ts"],
  ["apps/web/components/charts/severity-trend-chart.tsx", "apps/web/components/charts/chart-frame.tsx"],
  ["apps/web/components/charts/severity-trend-chart.tsx", "apps/web/components/charts/series.ts"],
  ["apps/web/components/charts/chart-frame.tsx", "packages/design/src/components/chart.tsx"],
  ["apps/web/app/o/[slug]/reviews/[id]/page.tsx", "apps/web/components/review/findings-table.tsx"],
  ["apps/web/app/o/[slug]/reviews/[id]/page.tsx", "packages/db/src/dashboard.ts"],
  ["apps/web/components/review/findings-table.tsx", "apps/web/components/review/finding-sheet.tsx"],
  ["apps/web/components/review/findings-table.tsx", "apps/web/components/ui/severity-badge.tsx"],
  ["apps/web/components/ui/severity-badge.tsx", "packages/design/src/index.ts"],
  ["apps/web/components/ui/stat.tsx", "packages/design/src/index.ts"],
  ["apps/web/lib/codebase-map.test.ts", "apps/web/lib/codebase-map.ts"],
  ["apps/web/app/api/ingest/handler.ts", "packages/db/src/schema.ts"],
  ["apps/web/app/api/ingest/handler.ts", "packages/schemas/src/findings.ts"],
  ["apps/web/app/api/ingest/handler.test.ts", "apps/web/app/api/ingest/handler.ts"],
  ["apps/web/app/api/github/webhook/handler.ts", "packages/github/src/client.ts"],
  ["apps/web/app/api/github/webhook/handler.ts", "packages/db/src/schema.ts"],
  ["apps/web/app/api/github/webhook/handler.test.ts", "apps/web/app/api/github/webhook/handler.ts"],
  ["packages/db/src/dashboard.ts", "packages/db/src/schema.ts"],
  ["packages/db/src/dashboard.ts", "packages/db/src/client.ts"],
  ["packages/db/src/dashboard.test.ts", "packages/db/src/dashboard.ts"],
  ["packages/reviewer/src/review.ts", "packages/ai/src/agent.ts"],
  ["packages/reviewer/src/review.ts", "packages/github/src/client.ts"],
  ["packages/reviewer/src/review.ts", "packages/index/src/index.ts"],
  ["packages/reviewer/src/review.ts", "packages/schemas/src/findings.ts"],
  ["packages/reviewer/src/review.ts", "packages/schemas/src/config.ts"],
  ["packages/reviewer/src/review.ts", "packages/logging/src/logger.ts"],
  ["packages/reviewer/src/synthesis.ts", "packages/ai/src/prompts.ts"],
  ["packages/reviewer/src/review.ts", "packages/reviewer/src/synthesis.ts"],
  ["packages/reviewer/src/review.ts", "packages/reviewer/src/incremental.ts"],
  ["packages/reviewer/src/incremental.ts", "packages/github/src/client.ts"],
  ["packages/reviewer/src/review.test.ts", "packages/reviewer/src/review.ts"],
  ["packages/ai/src/agent.ts", "packages/ai/src/tools.ts"],
  ["packages/ai/src/tools.ts", "packages/ai/src/agent.ts"],
  ["packages/ai/src/agent.ts", "packages/ai/src/prompts.ts"],
  ["packages/ai/src/tools.ts", "packages/index/src/index.ts"],
  ["packages/ai/src/agent.test.ts", "packages/ai/src/agent.ts"],
  ["packages/github/src/client.ts", "packages/github/src/comments.ts"],
  ["packages/github/src/client.test.ts", "packages/github/src/client.ts"],
  ["packages/index/src/index.ts", "packages/index/src/references.ts"],
  ["apps/action/src/main.ts", "packages/reviewer/src/review.ts"],
  ["apps/mcp/src/server.ts", "packages/reviewer/src/review.ts"],
  ["apps/mcp/src/server.ts", "packages/index/src/index.ts"],
  ["apps/cli/src/main.ts", "packages/reviewer/src/review.ts"],
  ["docs/adr/0002-primer-tokens-under-shadcn.md", "packages/design/src/brand.css"],
  ["CLAUDE.md", "docs/adr/0002-primer-tokens-under-shadcn.md"],
];

export const SAMPLE_GRAPH: MapGraph = {
  nodes: FILES.map(([id, kind, size, flags]) => ({ id, kind, size, ...flags })),
  edges: EDGES.map(([from, to]) => ({ from, to })),
};

export const SAMPLE_PR = { number: 147, title: "Primer tokens under shadcn, teal brand, OS-only theme" };
